#!/bin/bash

# Atom
function install_atom {
    # Variables
    NAME="Atom"
    PACKAGE="atom-amd64"
    REMOTE="https://atom.io/download/deb"
    # Download and install remote package
    install_remote_package $NAME $PACKAGE $REMOTE install_thirdparty
}