#!/bin/bash

# Install JetBrains Toolbox Utility from archive
function install_jetbrains_toolbox {
	NAME="JetBrains Toolbox"
	TARBALL=jetbrains-toolbox-1.14.5179
	CHECKSUM=faa7aa21ab275973f09ac49c1584a3948f4fdc76596286a51fc2a80c55afac04
	# Start
	echo_message header 'Begin '$NAME' installation...'
	
	# Download
	echo_message info 'Downloading zip file '$TARBALL'...'
	curl -O 
	
	# Verify download via sha256sum
	echo_message info 'Verifying download using SHA-256...'
	sha256sum ${TARBALL}.tar.gz | grep $CHECKSUM &> /dev/null
	EXITSTATUS=$?
	
	# Handling of verification
	# Checksum failure
	if [ $EXITSTATUS = 1]; then
		echo_message error 'Error: checksums do not match. Aborting...'
		whiptail --title "Error" --msgbox "Verification of $NAME download failed." 8 56
		rm ${TARBALL}.tar.gz
		thirdparty
	# Checksum success
	else
		# If checksum succeeds
		echo_message success "Checksums look good. Proceeding..."
		
		# Unpack tarball
		echo_message info 'Unpacking '$NAME' archive...'
		tar -xvf $TARBALL*.tar.gz
		
		# Moving package to /opt/ folder
		echo_message info 'Moving package to /opt/ folder...'
		superuser_do "mv jetbrains-toolbox-1.14.5179 /opt/"
		cd /opt/jetbrains-toolbox-1.14.5179
		
		# Run install script
		echo_message info 'Running install script...'
		echo_message warning 'This will require user input!'
		nohup ./jetbrains-toolbox &

		# Cleanup and finish
		echo_message success "Installation of '$TARBALL' complete."
		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 56
		thirdparty
		fi
}
